# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/ruby:3.1.1
      environment:
        BUNDLE_PATH: vendor/bundle
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        RAILS_ENV: test

workflows:
  version: 2
  test_workflow:
    jobs:
      - test

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: echo "This is teh job"
      # Restore Cached Dependencies
      # - type: cache-restore
      #   name: Restore bundle cache
      #   key: rails-bubbler-test-{{ checksum "Gemfile.lock" }}

      # # Bundle install dependencies
      # - run: bundle install --path vendor/bundle

      # # Cache Dependencies
      # - type: cache-save
      #   name: Store bundle cache
      #   key: rails-bubbler-test-{{ checksum "Gemfile.lock" }}
      #   paths:
      #     - vendor/bundle
      # - run: bundle exec rake test

