# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@1.0

defaults: &defaults
  docker:
    - image: cimg/ruby:3.1.1
      environment:
        BUNDLE_PATH: vendor/bundle
        BUNDLE_JOBS: 4
        BUNDLE_RETRY: 3
        RAILS_ENV: test

workflows:
  version: 2
  test_workflow:
    jobs:
      - test

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rake test

